
# Crawl stages.
# Muchoviaje feed.
muchoviaje :
  url: http://www.muchoviaje.com/cruceros/CRUCEROS.ASP
  language: es
  stages:

    stage1:
      selector: '#navieras ul a'
      # What attribute we want to fetch.
      fetch: 'href'

    stage2:
      selector: ".divItinerariolink"
      fetch: 'href'

    stage3:
      # TODO: Multiple selectors?
      selector: ".precioDetalles"
      fetch: 'results'

